<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../db/Database.php';
require_once __DIR__ . '/PropertyController.php';
session_start();

if (!isset($_SESSION['user_id'])) {
    header("Location: ../../login.php");
    exit;
}

$conn = Database::connect();
$userId = $_SESSION['user_id'];
$exportType = $_GET['type'] ?? '';
$format = $_GET['format'] ?? 'csv';

if (!in_array($exportType, ['favorites', 'my_properties'])) {
    $_SESSION['flash_message'] = 'Invalid export type.';
    header("Location: ../../profile.php");
    exit;
}

if (!in_array($format, ['csv', 'json', 'pdf'])) {
    $_SESSION['flash_message'] = 'Invalid export format.';
    header("Location: ../../profile.php");
    exit;
}

$userStmt = $conn->prepare("SELECT name FROM users WHERE id = :id");
$userStmt->execute(['id' => $userId]);
$userName = $userStmt->fetchColumn();
$safeUserName = preg_replace('/[^a-zA-Z0-9_-]/', '_', $userName);

$data = [];
$filename = '';

if ($exportType === 'favorites') {
    $stmt = $conn->prepare("
        SELECT p.id, p.title, p.description, p.price, p.area, p.status, p.posted_at as created_at,
               ST_Y(p.location::geometry) as lat, ST_X(p.location::geometry) as lng,
               u.name as owner_name, u.email as owner_email
        FROM saved_properties sp
        JOIN properties p ON sp.property_id = p.id
        JOIN users u ON p.user_id = u.id
        WHERE sp.user_id = :uid
        ORDER BY p.id DESC
    ");
    $stmt->execute(['uid' => $userId]);
    $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
    $filename = $safeUserName . '_favorite_properties_' . date('Y-m-d');
}else if ($exportType === 'my_properties') {
    $data = getUserProperties($userId);
    $filename = $safeUserName . '_my_properties_' . date('Y-m-d');
}

foreach ($data as &$property) {
    $facilityStmt = $conn->prepare("
        SELECT f.name 
        FROM property_facility pf 
        JOIN facilities f ON pf.facility_id = f.id 
        WHERE pf.property_id = :pid
    ");
    $facilityStmt->execute(['pid' => $property['id']]);
    $facilities = $facilityStmt->fetchAll(PDO::FETCH_COLUMN);
    $property['facilities'] = implode(', ', $facilities);
}

switch ($format) {
    case 'csv':
        exportCSV($data, $filename);
        break;
    case 'json':
        exportJSON($data, $filename);
        break;
    case 'pdf':
        exportPDF($data, $filename, $exportType);
        break;
}

function exportCSV($data, $filename) {
    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    
    if (!empty($data)) {
        fputcsv($output, ['REM - Real Estate Management System']);
        fputcsv($output, ['Export Generated:', date('F j, Y \a\t g:i A')]);
        fputcsv($output, ['Total Properties:', count($data)]);
        fputcsv($output, ['']);
        
        $headers = [
            'Property ID', 
            'Property Title', 
            'Description', 
            'Price (EUR)', 
            'Area (m²)', 
            'Listing Status', 
            'Latitude', 
            'Longitude', 
            'Available Facilities', 
            'Date Posted'
        ];
        
        if (isset($data[0]['owner_name'])) {
            $headers[] = 'Owner Full Name';
            $headers[] = 'Owner Email Address';
        }
        
        fputcsv($output, $headers);
        
        foreach ($data as $row) {
            $csvRow = [
                $row['id'],
                $row['title'],
                $row['description'],
                '€' . number_format($row['price'], 0, '.', ','),
                $row['area'] . ' m²',
                $row['status'] === 'for_sale' ? 'For Sale' : 'For Rent',
                $row['lat'] ?? 'N/A',
                $row['lng'] ?? 'N/A',
                !empty($row['facilities']) ? $row['facilities'] : 'None specified',
                date('M j, Y', strtotime($row['created_at'] ?? 'now'))
            ];
            
            if (isset($row['owner_name'])) {
                $csvRow[] = $row['owner_name'];
                $csvRow[] = $row['owner_email'];
            }
            
            fputcsv($output, $csvRow);
        }
        
        fputcsv($output, ['']);
        fputcsv($output, ['Generated by REM System']);
        fputcsv($output, ['Contact: admin@rem-system.local']);
    }
    
    fclose($output);
    exit;
}

function exportJSON($data, $filename) {
    header('Content-Type: application/json; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '.json"');
    
    $exportData = [
        'export_info' => [
            'system' => 'REM - Real Estate Management System',
            'export_date' => date('Y-m-d H:i:s'),
            'export_timestamp' => time(),
            'total_properties' => count($data),
            'format_version' => '1.0'
        ],
        'summary' => [
            'total_listings' => count($data),
            'for_sale' => count(array_filter($data, fn($p) => $p['status'] === 'for_sale')),
            'for_rent' => count(array_filter($data, fn($p) => $p['status'] === 'for_rent')),
            'average_price' => !empty($data) ? round(array_sum(array_column($data, 'price')) / count($data), 2) : 0,
            'total_area' => !empty($data) ? array_sum(array_column($data, 'area')) : 0
        ],
        'properties' => array_map(function($property) {
            return [
                'basic_info' => [
                    'id' => (int)$property['id'],
                    'title' => $property['title'],
                    'description' => $property['description'],
                    'status' => $property['status'],
                    'posted_date' => $property['created_at'] ?? null
                ],
                'pricing' => [
                    'price' => (float)$property['price'],
                    'currency' => 'EUR',
                    'price_formatted' => '€' . number_format($property['price'])
                ],
                'property_details' => [
                    'area_sqm' => (int)$property['area'],
                    'facilities' => !empty($property['facilities']) ? explode(', ', $property['facilities']) : []
                ],
                'location' => [
                    'latitude' => isset($property['lat']) ? (float)$property['lat'] : null,
                    'longitude' => isset($property['lng']) ? (float)$property['lng'] : null,
                    'coordinates_available' => isset($property['lat']) && isset($property['lng'])
                ],
                'owner_info' => isset($property['owner_name']) ? [
                    'name' => $property['owner_name'],
                    'email' => $property['owner_email']
                ] : null
            ];
        }, $data)
    ];
    
    echo json_encode($exportData, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
    exit;
}

function exportPDF($data, $filename, $exportType) {
    $queryParams = http_build_query([
        'type' => $exportType
    ]);
    header("Location: ../../export_pdf_preview.php?" . $queryParams);
    exit;
}

$_SESSION['flash_message'] = 'Export completed successfully.';
header("Location: ../../profile.php");
exit;
?>
