<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../services/PropertyService.php';
require_once __DIR__ . '/../db/Database.php';

class ExportController
{
    public static function getExportData($userId, $exportType)
    {
        if ($exportType === 'favorites') {
            return PropertyService::getFavoriteProperties($userId);
        } else {
            return PropertyService::getUserProperties($userId);
        }
    }

    public static function getExportFilename($userId, $exportType)
    {
        $conn = Database::connect();
        $userStmt = $conn->prepare("SELECT name FROM users WHERE id = :id");
        $userStmt->execute(['id' => $userId]);
        $userName = $userStmt->fetchColumn();
        $safeUserName = preg_replace('/[^a-zA-Z0-9_-]/', '_', $userName);

        if ($exportType === 'favorites') {
            return $safeUserName . '_favorite_properties_' . date('Y-m-d');
        } else {
            return $safeUserName . '_my_properties_' . date('Y-m-d');
        }
    }

    public static function generateCSV($data)
    {
        $output = fopen('php://temp', 'r+');
        fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

        if (!empty($data)) {
            fputcsv($output, ['REM - Real Estate Management System']);
            fputcsv($output, ['Export Generated:', date('F j, Y \a\t g:i A')]);
            fputcsv($output, ['Total Properties:', count($data)]);
            fputcsv($output, ['']);

            $headers = [
                'Property ID',
                'Property Title',
                'Description',
                'Price (EUR)',
                'Area (m²)',
                'Listing Status',
                'Latitude',
                'Longitude',
                'Available Facilities',
                'Date Posted'
            ];

            if (isset($data[0]['owner_name'])) {
                $headers[] = 'Owner Full Name';
                $headers[] = 'Owner Email Address';
            }

            fputcsv($output, $headers);

            foreach ($data as $row) {
                $csvRow = [
                    $row['id'],
                    $row['title'],
                    $row['description'],
                    '€' . number_format($row['price'], 0, '.', ','),
                    $row['area'] . ' m²',
                    $row['status'] === 'for_sale' ? 'For Sale' : 'For Rent',
                    $row['lat'] ?? 'N/A',
                    $row['lng'] ?? 'N/A',
                    !empty($row['facilities']) ? $row['facilities'] : 'None specified',
                    date('M j, Y', strtotime($row['created_at'] ?? 'now'))
                ];

                if (isset($row['owner_name'])) {
                    $csvRow[] = $row['owner_name'];
                    $csvRow[] = $row['owner_email'];
                }

                fputcsv($output, $csvRow);
            }

            fputcsv($output, ['']);
            fputcsv($output, ['Generated by REM System']);
            fputcsv($output, ['Contact: admin@rem-system.local']);
        }

        rewind($output);
        $csv = stream_get_contents($output);
        fclose($output);
        return $csv;
    }

    public static function generateJSON($data)
    {
        $exportData = [
            'export_info' => [
                'system' => 'REM - Real Estate Management System',
                'export_date' => date('Y-m-d H:i:s'),
                'export_timestamp' => time(),
                'total_properties' => count($data),
                'format_version' => '1.0'
            ],
            'summary' => [
                'total_listings' => count($data),
                'for_sale' => count(array_filter($data, fn($p) => $p['status'] === 'for_sale')),
                'for_rent' => count(array_filter($data, fn($p) => $p['status'] === 'for_rent')),
                'average_price' => !empty($data) ? round(array_sum(array_column($data, 'price')) / count($data), 2) : 0,
                'total_area' => !empty($data) ? array_sum(array_column($data, 'area')) : 0
            ],
            'properties' => array_map(function($property) {
                return [
                    'basic_info' => [
                        'id' => (int)$property['id'],
                        'title' => $property['title'],
                        'description' => $property['description'],
                        'status' => $property['status'],
                        'posted_date' => $property['created_at'] ?? null
                    ],
                    'pricing' => [
                        'price' => (float)$property['price'],
                        'currency' => 'EUR',
                        'price_formatted' => '€' . number_format($property['price'])
                    ],
                    'property_details' => [
                        'area_sqm' => (int)$property['area'],
                        'facilities' => !empty($property['facilities']) ? explode(', ', $property['facilities']) : []
                    ],
                    'location' => [
                        'latitude' => isset($property['lat']) ? (float)$property['lat'] : null,
                        'longitude' => isset($property['lng']) ? (float)$property['lng'] : null,
                        'coordinates_available' => isset($property['lat']) && isset($property['lng'])
                    ],
                    'owner_info' => isset($property['owner_name']) ? [
                        'name' => $property['owner_name'],
                        'email' => $property['owner_email']
                    ] : null
                ];
            }, $data)
        ];
        return json_encode($exportData, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
    }

    public static function getPDFData($data, $exportType)
    {
        return [
            'exportType' => $exportType,
            'data' => $data
        ];
    }
}
