<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../db/Database.php';
require_once __DIR__ . '/PropertyController.php';
session_start();

if (!isset($_SESSION['user_id'])) {
    header("Location: ../../login.php");
    exit;
}

$conn = Database::connect();
$userId = $_SESSION['user_id'];
$exportType = $_GET['type'] ?? '';
$format = $_GET['format'] ?? 'csv';

if (!in_array($exportType, ['favorites', 'my_properties'])) {
    $_SESSION['flash_message'] = 'Invalid export type.';
    header("Location: ../../profile.php");
    exit;
}

if (!in_array($format, ['csv', 'json', 'pdf'])) {
    $_SESSION['flash_message'] = 'Invalid export format.';
    header("Location: ../../profile.php");
    exit;
}

$userStmt = $conn->prepare("SELECT name FROM users WHERE id = :id");
$userStmt->execute(['id' => $userId]);
$userName = $userStmt->fetchColumn();
$safeUserName = preg_replace('/[^a-zA-Z0-9_-]/', '_', $userName);

$data = [];
$filename = '';

if ($exportType === 'favorites') {
    $stmt = $conn->prepare("
        SELECT p.id, p.title, p.description, p.price, p.area, p.status, p.posted_at as created_at,
               ST_Y(p.location::geometry) as lat, ST_X(p.location::geometry) as lng,
               u.name as owner_name, u.email as owner_email
        FROM saved_properties sp
        JOIN properties p ON sp.property_id = p.id
        JOIN users u ON p.user_id = u.id
        WHERE sp.user_id = :uid
        ORDER BY p.id DESC
    ");
    $stmt->execute(['uid' => $userId]);
    $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
    $filename = $safeUserName . '_favorite_properties_' . date('Y-m-d');
}else if ($exportType === 'my_properties') {
    $data = getUserProperties($userId);
    $filename = $safeUserName . '_my_properties_' . date('Y-m-d');
}

foreach ($data as &$property) {
    $facilityStmt = $conn->prepare("
        SELECT f.name 
        FROM property_facility pf 
        JOIN facilities f ON pf.facility_id = f.id 
        WHERE pf.property_id = :pid
    ");
    $facilityStmt->execute(['pid' => $property['id']]);
    $facilities = $facilityStmt->fetchAll(PDO::FETCH_COLUMN);
    $property['facilities'] = implode(', ', $facilities);
}

switch ($format) {
    case 'csv':
        exportCSV($data, $filename);
        break;
    case 'json':
        exportJSON($data, $filename);
        break;
    case 'pdf':
        exportPDF($data, $filename, $exportType);
        break;
}

function exportCSV($data, $filename) {
    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    
    if (!empty($data)) {
        fputcsv($output, ['REM - Real Estate Management System']);
        fputcsv($output, ['Export Generated:', date('F j, Y \a\t g:i A')]);
        fputcsv($output, ['Total Properties:', count($data)]);
        fputcsv($output, ['']);
        
        $headers = [
            'Property ID', 
            'Property Title', 
            'Description', 
            'Price (EUR)', 
            'Area (m²)', 
            'Listing Status', 
            'Latitude', 
            'Longitude', 
            'Available Facilities', 
            'Date Posted'
        ];
        
        if (isset($data[0]['owner_name'])) {
            $headers[] = 'Owner Full Name';
            $headers[] = 'Owner Email Address';
        }
        
        fputcsv($output, $headers);
        
        foreach ($data as $row) {
            $csvRow = [
                $row['id'],
                $row['title'],
                $row['description'],
                '€' . number_format($row['price'], 0, '.', ','),
                $row['area'] . ' m²',
                $row['status'] === 'for_sale' ? 'For Sale' : 'For Rent',
                $row['lat'] ?? 'N/A',
                $row['lng'] ?? 'N/A',
                !empty($row['facilities']) ? $row['facilities'] : 'None specified',
                date('M j, Y', strtotime($row['created_at'] ?? 'now'))
            ];
            
            if (isset($row['owner_name'])) {
                $csvRow[] = $row['owner_name'];
                $csvRow[] = $row['owner_email'];
            }
            
            fputcsv($output, $csvRow);
        }
        
        fputcsv($output, ['']);
        fputcsv($output, ['Generated by REM System']);
        fputcsv($output, ['Contact: admin@rem-system.local']);
    }
    
    fclose($output);
    exit;
}

function exportJSON($data, $filename) {
    header('Content-Type: application/json; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '.json"');
    
    $exportData = [
        'export_info' => [
            'system' => 'REM - Real Estate Management System',
            'export_date' => date('Y-m-d H:i:s'),
            'export_timestamp' => time(),
            'total_properties' => count($data),
            'format_version' => '1.0'
        ],
        'summary' => [
            'total_listings' => count($data),
            'for_sale' => count(array_filter($data, fn($p) => $p['status'] === 'for_sale')),
            'for_rent' => count(array_filter($data, fn($p) => $p['status'] === 'for_rent')),
            'average_price' => !empty($data) ? round(array_sum(array_column($data, 'price')) / count($data), 2) : 0,
            'total_area' => !empty($data) ? array_sum(array_column($data, 'area')) : 0
        ],
        'properties' => array_map(function($property) {
            return [
                'basic_info' => [
                    'id' => (int)$property['id'],
                    'title' => $property['title'],
                    'description' => $property['description'],
                    'status' => $property['status'],
                    'posted_date' => $property['created_at'] ?? null
                ],
                'pricing' => [
                    'price' => (float)$property['price'],
                    'currency' => 'EUR',
                    'price_formatted' => '€' . number_format($property['price'])
                ],
                'property_details' => [
                    'area_sqm' => (int)$property['area'],
                    'facilities' => !empty($property['facilities']) ? explode(', ', $property['facilities']) : []
                ],
                'location' => [
                    'latitude' => isset($property['lat']) ? (float)$property['lat'] : null,
                    'longitude' => isset($property['lng']) ? (float)$property['lng'] : null,
                    'coordinates_available' => isset($property['lat']) && isset($property['lng'])
                ],
                'owner_info' => isset($property['owner_name']) ? [
                    'name' => $property['owner_name'],
                    'email' => $property['owner_email']
                ] : null
            ];
        }, $data)
    ];
    
    echo json_encode($exportData, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
    exit;
}

function exportPDF($data, $filename, $exportType) {
    header('Content-Type: text/html; charset=utf-8');
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title><?= $exportType === 'favorites' ? 'Favorite Properties' : 'My Properties' ?></title>
        <style>
            @media print {
                body { margin: 0; font-size: 12pt; }
                .no-print { display: none; }
                .page-break { page-break-before: always; }
                .property { break-inside: avoid; }
            }
            
            body { 
                font-family: Arial, sans-serif; 
                margin: 20px; 
                line-height: 1.4;
            }
            
            .print-header {
                background-color: #f8f9fa;
                padding: 20px;
                border-radius: 8px;
                margin-bottom: 30px;
                text-align: center;
            }
            
            .header { 
                text-align: center; 
                margin-bottom: 30px; 
                border-bottom: 2px solid #333; 
                padding-bottom: 10px; 
            }
            
            .controls {
                text-align: center;
                margin-bottom: 20px;
                padding: 15px;
                background-color: #e9ecef;
                border-radius: 5px;
            }
            
            .btn {
                background-color: #007bff;
                color: white;
                border: none;
                padding: 10px 20px;
                margin: 5px;
                border-radius: 4px;
                cursor: pointer;
                text-decoration: none;
                display: inline-block;
            }
            
            .btn:hover {
                background-color: #0056b3;
            }
            
            .property { 
                margin-bottom: 20px; 
                padding: 15px; 
                border: 1px solid #ddd; 
                border-radius: 5px; 
                background-color: #fff;
            }
            
            .property-title { 
                font-size: 18px; 
                font-weight: bold; 
                color: #333; 
                margin-bottom: 10px; 
                border-bottom: 1px solid #eee;
                padding-bottom: 5px;
            }
            
            .property-details { 
                margin-bottom: 8px; 
            }
            
            .price { 
                font-weight: bold; 
                color: #2c5aa0; 
                font-size: 16px;
            }
            
            .facilities { 
                font-style: italic; 
                color: #666; 
            }
            
            .footer { 
                margin-top: 30px; 
                text-align: center; 
                font-size: 12px; 
                color: #666; 
                border-top: 1px solid #ddd;
                padding-top: 20px;
            }
            
            .property-grid {
                display: grid;
                gap: 20px;
            }
            
            @media screen and (min-width: 768px) {
                .property-grid {
                    grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
                }
            }
        </style>
        <script>
            function printPage() {
                window.print();
            }
            
            function downloadPDF() {
                window.print();
            }
            
            window.onload = function() {
                document.getElementById('printBtn').focus();
            }
        </script>
    </head>
    <body>
        <div class="print-header no-print">
            <h2>📄 Print Preview</h2>
            <p>Use the controls below to print or save as PDF</p>
        </div>
        
        <div class="controls no-print">
            <button id="printBtn" class="btn" onclick="printPage()">🖨️ Print / Save as PDF</button>
            <a href="../../profile.php" class="btn" style="background-color: #6c757d;">← Back to Profile</a>
        </div>
        
        <div class="header">
            <h1><?= $exportType === 'favorites' ? 'My Favorite Properties' : 'My Properties' ?></h1>
            <p>Exported on <?= date('F j, Y') ?></p>
            <p>Total Properties: <?= count($data) ?></p>
        </div>
        
        <?php if (empty($data)): ?>
            <div class="property">
                <p style="text-align: center; font-style: italic; color: #666;">No properties found.</p>
            </div>
        <?php else: ?>
            <div class="property-grid">
                <?php foreach ($data as $property): ?>
                    <div class="property">
                        <div class="property-title"><?= htmlspecialchars($property['title']) ?></div>
                        <div class="property-details"><strong>Description:</strong> <?= htmlspecialchars($property['description']) ?></div>
                        <div class="property-details price"><strong>Price:</strong> €<?= number_format($property['price']) ?></div>
                        <div class="property-details"><strong>Area:</strong> <?= $property['area'] ?> m²</div>
                        <div class="property-details"><strong>Status:</strong> <?= $property['status'] === 'for_sale' ? 'For Sale' : 'For Rent' ?></div>
                        <?php if (!empty($property['facilities'])): ?>
                            <div class="property-details facilities"><strong>Facilities:</strong> <?= htmlspecialchars($property['facilities']) ?></div>
                        <?php endif; ?>
                        <?php if (isset($property['owner_name'])): ?>
                            <div class="property-details"><strong>Owner:</strong> <?= htmlspecialchars($property['owner_name']) ?> (<?= htmlspecialchars($property['owner_email']) ?>)</div>
                        <?php endif; ?>
                        <div class="property-details"><strong>Posted:</strong> <?= date('F j, Y', strtotime($property['created_at'])) ?></div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        
        <div class="footer">
            <p>Generated by REM - Real Estate Management System</p>
            <p>Report generated on <?= date('F j, Y \a\t H:i') ?></p>
        </div>
    </body>
    </html>
    <?php
    exit;
}

$_SESSION['flash_message'] = 'Export completed successfully.';
header("Location: ../../profile.php");
exit;
?>
